runtime: python311  # Update this to match the Python version you are using
entrypoint: gunicorn -b :$PORT main:app
env_variables:
  OPENAI_API_KEY: YOURKEY

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
